### ISSUE TITLE
Combine our Github Page and Jekyll

### ISSUE THREAD

**Issue by KrisMcChes** [UnitedVendorsDC/UnitedVendorsDC.github.io#2]
Rempee: Combine our Github Page and Jekyll.
This is where we combine the two services to support the website. I will have to set this up in Github. I will use this guide, in case you want to follow along. 
http://jmcglone.com/guides/github-pages/

**Comment by KrisMcChes** [comment]
Rempee Comment from SE class: 
This is where we combine the two services to support the website. I will have to set this up in Github. I will use this guide, in case you want to follow along.

http://jmcglone.com/guides/github-pages/

**Comment by rempkay** [comment]
Jekyll is now in our repository.
