### ISSUE TITLE
Create a folder for the images and collect the images needed for the website.

### ISSUE THREAD

**Issue by rempkay** [UnitedVendorsDC/UnitedVendorsDC.github.io#21]
For all pages.

**Comment by KrisMcChes** [comment]
There is a folder "img" for assets, but it currently only has default pictures.
UV logo added to the folder.

**Comment by KrisMcChes** [comment]
@rempkay Shall we close it? We'll add the images as they're coming along the way.

**Comment by rempkay** [comment]
Yes sounds good!
